name: drink_story
description: "A new Flutter project."
publish_to: 'none'

# Поднимите build number, если предыдущий уже загружен в Play Console
version: 1.0.0+5

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.2.4
  flutter_riverpod: ^3.0.3
  just_audio: ^0.10.5
  audio_service: ^0.18.18
  mobile_scanner: ^7.1.2
  dio: ^5.9.0
  path_provider: ^2.1.5
  archive: ^4.0.7
  crypto: ^3.0.6
  url_launcher: ^6.3.2
  cryptography: ^2.7.0
  webview_flutter: ^4.13.0   # <-- перенесено сюда, второй блок dependencies удалён
  webview_flutter_android: ^4.10.5
  webview_flutter_wkwebview: ^3.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/public_key.pem
